### PR TITLE
feat: relax rack-test dependency to allow version 2

### PR DESCRIPTION
**Pull request by stanhu**
rack-test has a number of fixes and improvements:
https://github.com/rack/rack-test/blob/main/History.md

### CODE REVIEW

**Comment by bethesque** [comment]
See https://github.com/pact-foundation/pact-ruby/pull/271

**Comment by bethesque** [comment]
Sorry, see https://github.com/pact-foundation/pact-ruby/pull/268

**Comment by stanhu** [comment]
As far as I can tell, there shouldn't be any issues with this update: https://github.com/pact-foundation/pact-ruby/pull/268#issuecomment-1223629428

**Comment by bethesque** [comment]
What I'll do is open up the version for ruby, but lock it for the pact-ruby-standalone, so if there are any impacts, the ruby people will find them first!

**Comment by lsylvester** [comment]
For what it is worth I have implemented a producer and consumer using rack-test 2.X from my branch and didn't encounter any issues.

**Comment by bethesque** [comment]
Locked rack-test in pact-ruby-standalone https://github.com/pact-foundation/pact-ruby-standalone/commit/3fc12c928622d5b6dfd8a4f404a63b4f7190b83e

**Comment by bethesque** [comment]
Also in pact-cli https://github.com/pact-foundation/pact-ruby-cli/commit/b5585320677b20396b94d95b95b86cb7bf73d348

**Comment by bethesque** [comment]
New version of pact gem released with this change.

**Pull request merged**
