### PR TITLE
fix: always execute global and base states

### LINKED ISSUE #180: Base and Global set_up and tear_down do not execute when interaction has no provider state
Hi. My understanding from the [docs](https://github.com/pact-foundation/pact-ruby/wiki/Provider-states#base-state) is that base and global `set_up` and `tear_down` get executed for each interaction regardless of whether the interaction has a provider state defined.
However, I have noticed that base and global `set_up` and `tear_down` only seem to be executed for interactions that have a provider state. Can someone please confirm? Thanks.

Here is an example: https://github.com/abhitrivedi/pact-ruby-e2e-example

I've added a global and base state to pact_helper.rb but since the consumer interaction has no provider state specified, those global and base states do not get executed.

### PR DESCRIPTION
**Pull request by abhitrivedi**
Ensure that global and base states are executed regardless of
whether interaction defines a provider state, as described in
the docs.

Fixes #180

### CODE REVIEW

**Comment by bethesque** [comment]
This has ramifications for all the pact implementations that currently use the pact-ruby-standalone. I'm going to have to think them through. It could be a breaking change, so we may have to make it configurable.

**Comment by abhitrivedi** [comment]
Sounds fair. I'd love to discuss alternatives. The goal is to allow provider to have some kind of set_up and tear_down mechanism that is global and does not depend on whether consumer interaction prescribes a provider state.

**Comment by abhitrivedi** [comment]
Also, I could be wrong, but it looks like this issue only affects versions since we started supporting multiple provider states.

**Comment by bethesque** [comment]
Ah, good point! So it may just be fixing a bug I introduced. I'll have a look and a think.

**Comment by iamvery** [comment]
I think I just ran into this. I am running 1.36.0, and I have a pact which does not specify any provider state. However, it does assume that some global state is set up in the `set_up` block. On this version, the `set_up` block does not seem to execute for this pact, which results in a pact failure.

I'm interested in the release of this fix! Thank you ❤️💙💚💛💜

**Comment by bethesque** [comment]
I'll release it today.

**Comment by bethesque** [comment]
1.36.2 is out, and 1.61.2 of the standalone.

**Pull request merged**
