### PR TITLE
feat(CI): use setup-ruby's bundle installer and cache

### PR DESCRIPTION
**Pull request by josephyi**
* use setup-ruby to run bundle install
* refactor `BUNDLE_GEMFILE` to the job level

Test runs with these changes can be observed here - https://github.com/josephyi/pact-ruby/actions/workflows/test.yml

### CODE REVIEW

**Comment by bethesque** [comment]
Why is the `BUNDLE_GEMFILE: active-support.gemfile` removed?

**Comment by bethesque** [comment]
Oh, I see! Sorry, was not reading properly.

**Comment by bethesque** [comment]
Thanks! 

I only realised after I'd pressed the "merge" button, but this is a "chore" not a "feat". "feat" is only for things that affect the user and should be included in release notes.

**Comment by josephyi** [comment]
> Thanks!
> 
> I only realised after I'd pressed the "merge" button, but this is a "chore" not a "feat". "feat" is only for things that affect the user and should be included in release notes.

Ooh sorry about that, makes sense!

**Pull request merged**
